version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: url_shortener
    ports:
      - "3306:3306"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
